/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DasherDocumentFrame.java
 *
 * Created on Oct 21, 2009, 1:07:46 PM
 */

package dasher.ui;

import java.util.logging.Logger;

/**
 *
 * @author joshua
 */
public class DasherDocumentFrame extends javax.swing.JInternalFrame {

    /** Creates new form DasherDocumentFrame */
    public DasherDocumentFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDasherView = new dasher.ui.JDasherView();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(800, 600));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jDasherView, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jDasherView, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Variables and Properties">

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dasher.ui.JDasherView jDasherView;
    // End of variables declaration//GEN-END:variables

    public JDasherView getjDasherView() {
        return jDasherView;
    }
    /**
     * The Logger for this class.
     */
    private static Logger log = Logger.getLogger(DasherDocumentFrame.class.getName());

    // </editor-fold>

}
